spring.application.name=client-service
server.port=8084
management.endpoints.web.exposure.include=health,info,prometheus,metrics
management.metrics.tags.application=client-service
services.study.url=${SERVICES_STUDY_URL:http://localhost:8081}
