apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: studybridge-v2
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/hyunsoo1/studybridge-v2.git
    targetRevision: HEAD
    path: k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: studybridge
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
