spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:3000"
              - "http://localhost:5173"
            allowedMethods: "*"
            allowedHeaders: "*"
      routes:
        - id: study-service
          uri: http://study-service:8081
          predicates:
            - Path=/api/studies/**
        - id: comment-service
          uri: http://comment-service:8083
          predicates:
            - Path=/api/comments/**
        - id: apply-service
          uri: http://apply-service:8082
          predicates:
            - Path=/api/applications/**
        - id: notification-service-api
          uri: http://notification-service:8085
          predicates:
            - Path=/api/notifications/**
        - id: notification-service-flux
          uri: http://notification-service:8085
          predicates:
            - Path=/notifications/flux
        - id: client-service
          uri: http://client-service:8084
          predicates:
            - Path=/client/**

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway
