spring.application.name=study-service
server.port=8081
management.endpoints.web.exposure.include=health,info,prometheus,metrics
management.metrics.tags.application=study-service

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3307/studybridge?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul&characterEncoding=UTF-8}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:root1234}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.show-sql=false
